name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and run build
        run: |
          npm ci
          npm run build

      - name: Start application
        run: npm start

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v6
