name: Cypress Tests

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies and run build
        run: |
        npm i
        npm run

      - name: Start application
        run: npx cypress run --record --key 3c8528f8-696f-4d0d-bade-72427454f9e0

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v6
